name: test

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "repo"
        default: "tile-ai/tilelang"
      branch:
        description: "branch"
        default: "main"
  # schedule:
  #   - cron: '0 2 * * *'

jobs:
  release:
    runs-on: [self-hosted]
    steps:
      - run: |
          mkdir -p dist
          wget -P dist/ https://github.com/tile-ai/tilelang-nightly/releases/download/0.1.1%2Bfe02922/tilelang-0.1.1+fe02922.ubuntu.18.4.cu121-cp39-cp39-linux_x86_64.whl
      - run: ls -lah dist/
      - run: |
          tag_version=0.1.1+fe02922
          echo "TAG_VERSION=$tag_version" >> $GITHUB_ENV
          find dist -type f ! -name "*${tag_version}*" -delete
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_VERSION }}
          files: dist/*
          token: ${{ secrets.GITHUB_TOKEN }} 
      - name: Clone wheel index
        run: git clone https://$WHL_TOKEN@github.com/tile-ai/whl.git tilelang-whl
        env:
          WHL_TOKEN: ${{ secrets.WHL_TOKEN }}
  
      - name: Update wheel index
        run: python3 update_whl_index.py
  
      - name: Push wheel index
        run: |
          cd tilelang-whl
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "update nightly whl"
          git push https://$WHL_TOKEN@github.com/tile-ai/whl.git main
